### ISSUE TITLE
Make test scenario for azdev extension generate command in design document

### ISSUE THREAD

**Issue by bquantump** [bquantump/azure-cli-dev-tools#5]
The design doc is [here](https://microsoft-my.sharepoint.com/:w:/r/personal/stevens_microsoft_com/_layouts/15/guestaccess.aspx?e=4%3AKbJoob&at=9&share=EX9UNjtrXxtOtK3t5J6RzncB3BwMNOgFHNzR6ITGuHnBMQ).

**Comment by haroldrandom** [comment]
Will the scenario test be unit test/integration test written in azdev or just functional test listed like items on Design Docs?

**Comment by bquantump** [comment]
It should be a unit test in azdev. This would be a pytest.
